testing login on docker_2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,7 +50,30 @@ jobs:
       working-directory: ${{ secrets.TERRAFORM_DIR }}
 
    
-     
+     # step 4. Deploy Docker image to ec2
+    - name: Deploy Docker image to EC2
+      run: |
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ secrets.EC2_SSH_KEY}}
+        chmod 600 ${{ secrets.EC2_SSH_KEY }}
+        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.HOST_USER }}@$EC2_PUBLIC_IP << 'EOF'
+          
+        if ! [ -x "$(command -v docker)" ]; then
+            sudo yum update -y
+            sudo yum install -y docker
+            sudo systemctl start docker
+            sudo systemctl enable docker
+        fi  
+
+    
+        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets. DOCKERHUB_USERNAME }} --password-stdin
+          
+        if [ $? -eq 0 ]; then
+          echo "Docker login successful!"
+        else
+          echo "Docker login failed. Please check your credentials."
+          exit 1
+        fi      
+        EOF
       #        sudo docker pull crisxyrus/app-image:latest
 
           # Stop and remove any existing container with the same name
